# Permalinks
#

plugins:
  - jekyll-paginate
  
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
#title:               Lanyon
title:               'I-Chieh Wei (Sam Wei)'

#tagline:             'A Jekyll theme'
tagline:             'Research at the intersection of music and AI technology'

#description:         'A reserved <br> <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         'I-Chieh Wei (Sam Wei) <br> <br> Research assistant <br> MCTLab, Academia Sinica, Taiwan'

#url:                 http://lanyon.getpoole.com
url:                 'https://sma1033.github.io/site/'
baseurl:             '/site'
paginate:            4

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
